{
  "name": "test_failure",
  "status": "failed",
  "statusDetails": {
    "message": "AssertionError: assert False",
    "trace": "def test_failure():\n>       assert False\nE       assert False\n\npytest_Allure.py:5: AssertionError"
  },
  "start": 1627290573460,
  "stop": 1627290573460,
  "uuid": "2cbea39e-bab0-4c4f-bc83-221b7f688530",
  "historyId": "31c923f664d3e35577cfb38e95e11bd9",
  "testCaseId": "764cd8680d2b2704daddbc082e5cc6d5",
  "fullName": "pytest_Allure#test_failure",
  "labels": [
    {
      "name": "suite",
      "value": "pytest_Allure"
    },
    {
      "name": "host",
      "value": "LAPTOP-V2RHK3K3"
    },
    {
      "name": "thread",
      "value": "24240-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "pytest_Allure"
    }
  ]
}