{
  "name": "test_04",
  "status": "failed",
  "statusDetails": {
    "message": "AssertionError: assert 11 == 12",
    "trace": "self = <test_01.TestFCArequest object at 0x000002347FF7BC70>\n\n    @pytest.mark.run(order=2)\n    def test_04(self):\n>       assert 11 == 12\nE       assert 11 == 12\n\ntest_01.py:54: AssertionError"
  },
  "start": 1627897165693,
  "stop": 1627897165693,
  "uuid": "2cf5a7a5-5b52-46ef-9f5b-e3e8cc79f147",
  "historyId": "1683b8a74e22a11bf95199ffba07050b",
  "testCaseId": "9c0aecd24b4ae101f67f6557855fe318",
  "fullName": "test_01.TestFCArequest#test_04",
  "labels": [
    {
      "name": "tag",
      "value": "run(order=2)"
    },
    {
      "name": "suite",
      "value": "test_01"
    },
    {
      "name": "subSuite",
      "value": "TestFCArequest"
    },
    {
      "name": "host",
      "value": "LAPTOP-V2RHK3K3"
    },
    {
      "name": "thread",
      "value": "29340-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "test_01"
    }
  ]
}